"""
Django settings for MyDjango project.

Generated by 'django-admin startproject' using Django 2.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

#### 项目路径：
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

####密钥：
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3jyj4vzj%^ydofn+osuy_=vgw4#-jix#k!&sq$-_%t06ep64u0'

#### 调试模式：（调试状态时是单线程，生成模式时勿用）
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#### 域名访问权限：
ALLOWED_HOSTS = []


#APP列表：
# Application definition

INSTALLED_APPS = [
    ### 内置的后台管理系统：
    'django.contrib.admin',
    ### 内置的用户认证系统：
    'django.contrib.auth',
    ### 所有model元数据：
    'django.contrib.contenttypes',
    ### 会话，表示当前访问网站的用户身份：
    'django.contrib.sessions',
    ### 消息提示：
    'django.contrib.messages',
    ### 静态资源的路径：
    'django.contrib.staticfiles',
    ### 注册自己的APP（需要手动配置，否则不工作）：
    'index',
    'Douban',
]

#### 中间件是request和response对象之间的钩子
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MyDjango.urls'

TEMPLATES = [
    {
        ### 定义模版引擎：
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        ### 设置模板路径
        'DIRS': [],
        #### 是否在App里查找模板文件
        'APP_DIRS': True,
        ### 用于RequestContext上下文的调用函数
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MyDjango.wsgi.application'

### 数据库设置：(需要手动设置)
# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

#### 数据库配置，默认是sqlite，Django2.2使用mysqlclient或pymysql模块连接MySQL

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

# export PATH=$PATH:/usr/local/mysql/bin
# OSError: mysql_config not found
# pip install mysqlclient
# pip install pymysql
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'douban',
        'USER': 'root',
        'PASSWORD': 'chenqiong',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
    # 生产环境有可能连接第二个数据库
    # 'db2': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'mydatabase',
    #     'USER': 'mydatabaseuser',
    #     'PASSWORD': 'mypassword',
    #     'HOST': '127.0.0.1',
    #     'PORT': '3307',
    # }
}

### 密码认证配置：
# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE =  'en-us'  #'utf-8'  #'en-us'

TIME_ZONE = 'UTC'    #代表中国的东八区'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

### 静态目录设置：
STATIC_URL = '/static/'
